# dist: trusty
language: ruby
before_install:
  - gem --version
  - gem update bundler
  - gem --version
  - bash gemfiles/setup.sh

jobs:
  fast_finish: true
  include:
    - rvm: 2.6
      env: STACK_VERSION=1.7.6 DOCKER_IMAGE=elasticsearch
      gemfile: gemfiles/Gemfile.elasticsearch-1.x
    - rvm: 2.6
      env: STACK_VERSION=2.3 DOCKER_IMAGE=elasticsearch
      gemfile: gemfiles/Gemfile.elasticsearch-2.x
    - rvm: 2.6
      env: STACK_VERSION=5.6.16
      gemfile: gemfiles/Gemfile.elasticsearch-5.x
    - rvm: 2.6
      env: STACK_VERSION=6.8.16
      gemfile: gemfiles/Gemfile.elasticsearch-6.x
    - rvm: 2.6
      env: STACK_VERSION=7.13.2
      gemfile: gemfiles/Gemfile.elasticsearch-7.x
    - rvm: 2.7
      env: STACK_VERSION=6.8.16
      gemfile: gemfiles/Gemfile.elasticsearch-6.x
    - rvm: 2.7
      env: STACK_VERSION=7.13.2
      gemfile: gemfiles/Gemfile.elasticsearch-7.x
    - rvm: 2.7
      env: STACK_VERSION=8.2.1
      gemfile: gemfiles/Gemfile.elasticsearch-8.x
    - rvm: 3.0
      env: STACK_VERSION=6.8.16
      gemfile: gemfiles/Gemfile.elasticsearch-6.x
    - rvm: 3.0
      env: STACK_VERSION=7.13.2
      gemfile: gemfiles/Gemfile.elasticsearch-7.x
    - rvm: 2.6
      env: STACK_VERSION=1.3.3 DOCKER_IMAGE=opensearchproject/opensearch
      gemfile: gemfiles/Gemfile.opensearch-2.x
    - rvm: 2.6
      env: STACK_VERSION=2.0.1 DOCKER_IMAGE=opensearchproject/opensearch
      gemfile: gemfiles/Gemfile.opensearch-2.x
