#!/usr/bin/env ruby
# frozen_string_literal: true

$LOAD_PATH.unshift File.expand_path('../lib', __dir__)

require 'esse'
require 'esse/cli'

Esse::CLI::ExtensionsLoader.load!

Esse::CLI.with_friendly_errors do
  Esse::CLI.start(ARGV)
end
