require_relative 'deprecations/deprecate'
require_relative 'deprecations/index_backend_delegator'
require_relative 'deprecations/index'
require_relative 'deprecations/cluster'
require_relative 'deprecations/repository'
