name: build
on: [push, pull_request]
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        ruby: [2.6.9, 2.7.7, 3.0.3, 3.1.2, 3.2.2]
        include:
          - gemfile: gemfiles/Gemfile.elasticsearch-1.x
            stack: elasticsearch:1.7.6
            stack_version: "1.7.6"
            allow_failure: true
          - gemfile: gemfiles/Gemfile.elasticsearch-2.x
            stack: elasticsearch:2.4.6
            stack_version: "2.4.6"
            allow_failure: true
          - gemfile: gemfiles/Gemfile.elasticsearch-5.x
            stack: elasticsearch:5.6.16
            stack_version: "5.6.16"
            allow_failure: true
          - gemfile: gemfiles/Gemfile.elasticsearch-6.x
            stack: elasticsearch:6.8.16
            stack_version: "6.8.16"
            allow_failure: false
          - gemfile: gemfiles/Gemfile.elasticsearch-7.x
            stack: elasticsearch:7.13.2
            stack_version: "7.13.2"
            allow_failure: false
          - gemfile: gemfiles/Gemfile.elasticsearch-8.x
            stack: elasticsearch:8.4.2
            stack_version: "8.4.2"
            allow_failure: false
          - gemfile: gemfiles/Gemfile.opensearch-1.x
            stack: opensearch:1.3.3
            stack_version: "1.3.3"
            allow_failure: false
          - gemfile: gemfiles/Gemfile.opensearch-2.x
            stack: opensearch:2.0.1
            stack_version: "2.0.1"
            allow_failure: false
    runs-on: ubuntu-latest
    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
      STACK_VERSION: ${{ matrix.stack_version }}
      ESSE_URL: http://localhost:9200
    continue-on-error: ${{ matrix.allow_failure }}
    steps:
      - uses: actions/checkout@v3
      - name: Configure sysctl limits
        run: |
          sudo swapoff -a
          sudo sysctl -w vm.swappiness=1
          sudo sysctl -w fs.file-max=262144
          sudo sysctl -w vm.max_map_count=262144
      - uses: marcosgz/oe-search@v1
        with:
          stack: ${{ matrix.stack }}
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
      - name: Run tests
        run: |
          bundle exec rspec --require ./spec/suppress_pending_formatter.rb --format SuppressPendingFormatter
